/** A method file to emit: a neutral name and its content; the adapter maps the name to a harness path. */
export interface MethodFile {
  readonly name: string;
  readonly contents: string;
}

/** The harness-neutral method materials an adapter places for its harness. */
export interface MethodMaterials {
  /** The generic governance baselines — tool-authored, reconciled each run: updated while unedited, preserved once the project edits them. */
  readonly baselines: readonly MethodFile[];
  /** The clew skills — tool-authored, reconciled each run: updated while unedited, preserved once the project edits them. */
  readonly skills: readonly MethodFile[];
  /** The project stubs — seeded once, never written over. */
  readonly stubs: readonly MethodFile[];
}

/** What an adapter did: the method files written to the tool's version, the project stubs newly seeded, and the method files preserved because the project has edited them. */
export interface EmittedMethod {
  readonly written: readonly string[];
  readonly seeded: readonly string[];
  readonly preserved: readonly string[];
}

/** Options for an emission. */
export interface EmitOptions {
  /** Seed the project-owned files (stubs, index)? False on a re-run, which refreshes only the tool-owned method. */
  readonly seedProjectFiles?: boolean;
}

/** The tool tag a method file's marker carries; the marker itself is built with the file's content hash in `reconcile.ts`. */
export const METHOD_MARKER = "GENERATED BY CLEW";
