import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "vitest";
import { methodMarker, reconcileMethodFile } from "./reconcile.js";

async function tempFile(contents?: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), "clew-reconcile-"));
  const path = join(dir, "file.md");
  if (contents !== undefined) {
    await writeFile(path, contents, "utf8");
  }
  return path;
}

describe("reconciling a method file", () => {
  test("writes the tool version when the file is absent", async () => {
    const path = await tempFile();

    expect(await reconcileMethodFile(path, "body\n")).toBe("written");
    expect(await readFile(path, "utf8")).toContain("body");
  });

  test("updates an unedited file to the tool's new body", async () => {
    const path = await tempFile();
    await reconcileMethodFile(path, "old body\n");

    expect(await reconcileMethodFile(path, "new body\n")).toBe("written");
    expect(await readFile(path, "utf8")).toContain("new body");
  });

  test("preserves a file the project has edited", async () => {
    const stale = `${methodMarker("0".repeat(64))}\n\nedited body\n`;
    const path = await tempFile(stale);

    expect(await reconcileMethodFile(path, "body\n")).toBe("preserved");
    expect(await readFile(path, "utf8")).toContain("edited body");
  });

  test("preserves a file that carries no clew marker", async () => {
    const own = "the project's own file\n";
    const path = await tempFile(own);

    expect(await reconcileMethodFile(path, "body\n")).toBe("preserved");
    expect(await readFile(path, "utf8")).toBe(own);
  });

  test("migrates a pre-hash marked file to the hashed marker", async () => {
    const preHash =
      "<!-- GENERATED BY CLEW — do not edit; re-run `clew setup` to regenerate. -->\n\nold body\n";
    const path = await tempFile(preHash);

    expect(await reconcileMethodFile(path, "fresh body\n")).toBe("written");
    const written = await readFile(path, "utf8");
    expect(written).toContain("sha256:");
    expect(written).toContain("fresh body");
  });

  test("keeps YAML frontmatter at line 1 — the marker goes after it", async () => {
    const path = await tempFile();
    const skill = "---\nname: clew-x\ndescription: y\n---\n\n# Body\n";

    expect(await reconcileMethodFile(path, skill)).toBe("written");
    const written = await readFile(path, "utf8");
    expect(written.startsWith("---\n")).toBe(true);
    expect(written.indexOf("sha256:")).toBeGreaterThan(
      written.indexOf("---\nname"),
    );
    expect(written.indexOf("<!--")).toBeGreaterThan(written.lastIndexOf("---"));
  });

  test("a pristine frontmatter file round-trips; an edit is preserved", async () => {
    const path = await tempFile();
    const skill = "---\nname: clew-x\n---\n\n# Body\n";
    await reconcileMethodFile(path, skill);

    expect(await reconcileMethodFile(path, skill)).toBe("written");

    const marked = await readFile(path, "utf8");
    await writeFile(path, marked.replace("# Body", "# Edited body"), "utf8");
    expect(await reconcileMethodFile(path, skill)).toBe("preserved");
    expect(await readFile(path, "utf8")).toContain("# Edited body");
  });
});
