import type { GeneratedFile, SpecSet } from "@ariadne-thread/core";
import { ConTraceables, SwTraceables, verifies } from "@ariadne-thread/trace";
import { describe, expect, test } from "vitest";
import { createTypeScriptGenerator } from "./index.js";

const specSets: SpecSet[] = [
  {
    name: "CON",
    specs: [
      {
        id: "CON-012",
        lens: "CON",
        filename: "CON-012-owned.md",
        status: "active",
      },
    ],
  },
  {
    name: "SW",
    specs: [
      {
        id: "SW-016",
        lens: "SW",
        filename: "SW-016-promote.md",
        status: "active",
      },
      {
        id: "SW-017",
        lens: "SW",
        filename: "SW-017-finalize.md",
        status: "active",
      },
    ],
  },
];

async function generate(
  sets: readonly SpecSet[],
): Promise<readonly GeneratedFile[]> {
  return createTypeScriptGenerator().generate(sets, {
    outputDir: "src/ariadne/traceables",
  });
}

function fileAt(
  files: readonly GeneratedFile[],
  path: string,
): GeneratedFile | undefined {
  return files.find((file) => file.path === path);
}

describe("typescript generator output", () => {
  verifies(
    [
      SwTraceables.SW_018_TYPESCRIPT_OUTPUT,
      ConTraceables.CON_012_GENERATED_FILES_TOOL_OWNED,
    ],
    () => {
      test("declares its default output directory", () => {
        expect(createTypeScriptGenerator().defaultOutputDir).toBe(
          "src/ariadne/traceables",
        );
      });

      test("emits one string-enum file per spec set, member name from the filename", async () => {
        const files = await generate(specSets);

        const con = fileAt(files, "ConTraceables.ts");
        expect(con?.contents).toContain(
          "THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY",
        );
        expect(con?.contents).toContain(
          "@clew homepage: https://ariadne-thread.io",
        );
        expect(con?.contents).toContain("@clew connector-type: req-as-code");
        expect(con?.contents).toContain("@clew generator-type: typescript");
        expect(con?.contents).toContain("@clew spec-set: CON");
        expect(con?.contents).toContain("export enum ConTraceables {");
        expect(con?.contents).toContain('CON_012_OWNED = "CON-012",');

        const sw = fileAt(files, "SwTraceables.ts");
        expect(sw?.contents).toContain("export enum SwTraceables {");
        expect(sw?.contents).toContain('SW_016_PROMOTE = "SW-016",');
        expect(sw?.contents).toContain('SW_017_FINALIZE = "SW-017",');
      });

      test("marks a deprecated spec's member with an @deprecated JSDoc; others have none", async () => {
        const files = await generate([
          {
            name: "SW",
            specs: [
              {
                id: "SW-016",
                lens: "SW",
                filename: "SW-016-promote.md",
                status: "active",
              },
              {
                id: "SW-018",
                lens: "SW",
                filename: "SW-018-output.md",
                status: "deprecated",
              },
            ],
          },
        ]);

        const sw = fileAt(files, "SwTraceables.ts");
        expect(sw?.contents).toContain(
          '  /** @deprecated */\n  SW_018_OUTPUT = "SW-018",',
        );
        // The active member carries no deprecation; only the deprecated one does.
        expect(sw?.contents).toContain('  SW_016_PROMOTE = "SW-016",');
        expect((sw?.contents.match(/@deprecated/g) ?? []).length).toBe(1);
      });

      test("reads its emitted traceables back, round-tripping ids and deprecation (ARCH-004)", async () => {
        const generator = createTypeScriptGenerator();
        const sets: SpecSet[] = [
          {
            name: "SW",
            specs: [
              {
                id: "SW-016",
                lens: "SW",
                filename: "SW-016-promote.md",
                status: "active",
              },
              {
                id: "SW-018",
                lens: "SW",
                filename: "SW-018-output.md",
                status: "deprecated",
              },
            ],
          },
        ];
        const files = await generator.generate(sets, {
          outputDir: "src/ariadne/traceables",
        });

        // Read every emitted file back; only the enum members are traceables, so
        // the helper module and README contribute none.
        const universe = generator.readTraceables(files);

        expect(universe).toEqual([
          { id: "SW-016", deprecated: false },
          { id: "SW-018", deprecated: true },
        ]);
      });

      test("emits a helper module re-exporting the enums with the anchoring utility", async () => {
        const files = await generate(specSets);

        const helper = fileAt(files, "index.ts");
        expect(helper?.contents).toContain(
          'import { ConTraceables } from "./ConTraceables.js";',
        );
        expect(helper?.contents).toContain(
          'import { SwTraceables } from "./SwTraceables.js";',
        );
        expect(helper?.contents).toContain(
          "export { ConTraceables, SwTraceables };",
        );
        expect(helper?.contents).toContain(
          "export type TraceableId = ConTraceables | SwTraceables;",
        );
        expect(helper?.contents).toContain(
          "export type TraceableIds = TraceableId | readonly [TraceableId, ...TraceableId[]];",
        );
        expect(helper?.contents).toContain(
          "export function realizes<Value>(ids: TraceableIds, value: Value): Value;",
        );
        // The decorator overload: ids only, returning a no-op class/method decorator.
        expect(helper?.contents).toContain(
          "): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;",
        );
        expect(helper?.contents).toContain(
          "export function verifies(ids: TraceableIds, run: () => void)",
        );
        // The concerns relation: a function/decorator marker and a type marker.
        expect(helper?.contents).toContain(
          "export function concerns<Value>(ids: TraceableIds, value: Value): Value;",
        );
        expect(helper?.contents).toContain(
          "export type Concerns<Id extends TraceableIds, T> = T & { readonly __concerns?: Id };",
        );
        expect(helper?.contents).toContain(
          "export type Realizes<Id extends TraceableIds, T> = T & { readonly __realizes?: Id };",
        );
        // The JSDoc examples use a real member drawn from the first traceable.
        expect(helper?.contents).toContain("@example");
        expect(helper?.contents).toContain("ConTraceables.CON_012_OWNED");
      });

      test("emits one file per set, the helper module, and a README", async () => {
        const files = await generate(specSets);

        expect(files.map((file) => file.path)).toEqual([
          "ConTraceables.ts",
          "SwTraceables.ts",
          "index.ts",
          "README.md",
        ]);
      });

      test("emits a README documenting the markers", async () => {
        const files = await generate(specSets);

        const readme = fileAt(files, "README.md");
        expect(readme?.contents).toContain("# Traceables");
        expect(readme?.contents).toContain("concerns");
        expect(readme?.contents).toContain("ConTraceables.CON_012_OWNED");
      });

      test("is deterministic: the same spec sets produce byte-identical output", async () => {
        const first = await generate(specSets);
        const second = await generate(specSets);

        expect(second).toEqual(first);
      });
    },
  );
});
