import type { GeneratedFile, SpecSet } from "@ariadne-thread/core";
import { ConTraceables, SwTraceables, verifies } from "@ariadne-thread/trace";
import { describe, expect, test } from "vitest";
import { createTypeScriptGenerator } from "./index.js";

const specSets: SpecSet[] = [
  {
    name: "CON",
    traceables: [{ id: "CON-012", lens: "CON", filename: "CON-012-owned.md" }],
  },
  {
    name: "SW",
    traceables: [
      { id: "SW-016", lens: "SW", filename: "SW-016-promote.md" },
      { id: "SW-017", lens: "SW", filename: "SW-017-finalize.md" },
    ],
  },
];

async function generate(
  sets: readonly SpecSet[],
): Promise<readonly GeneratedFile[]> {
  return createTypeScriptGenerator().generate(sets, {
    outputDir: "src/ariadne/traceables",
  });
}

function fileAt(
  files: readonly GeneratedFile[],
  path: string,
): GeneratedFile | undefined {
  return files.find((file) => file.path === path);
}

describe("typescript generator output", () => {
  verifies(
    [
      SwTraceables.SW_018_TYPESCRIPT_OUTPUT,
      ConTraceables.CON_012_GENERATED_FILES_TOOL_OWNED,
    ],
    () => {
      test("declares its default output directory", () => {
        expect(createTypeScriptGenerator().defaultOutputDir).toBe(
          "src/ariadne/traceables",
        );
      });

      test("emits one string-enum file per spec set, member name from the filename", async () => {
        const files = await generate(specSets);

        const con = fileAt(files, "ConTraceables.ts");
        expect(con?.contents).toContain(
          "THIS FILE IS GENERATED BY ARIADNE-THREAD - DO NOT EDIT MANUALLY",
        );
        expect(con?.contents).toContain(
          "@ariadne-thread homepage: https://ariadne-thread.io",
        );
        expect(con?.contents).toContain(
          "@ariadne-thread connector-type: req-as-code",
        );
        expect(con?.contents).toContain(
          "@ariadne-thread generator-type: typescript",
        );
        expect(con?.contents).toContain("@ariadne-thread spec-set: CON");
        expect(con?.contents).toContain("export enum ConTraceables {");
        expect(con?.contents).toContain('CON_012_OWNED = "CON-012",');

        const sw = fileAt(files, "SwTraceables.ts");
        expect(sw?.contents).toContain("export enum SwTraceables {");
        expect(sw?.contents).toContain('SW_016_PROMOTE = "SW-016",');
        expect(sw?.contents).toContain('SW_017_FINALIZE = "SW-017",');
      });

      test("emits a helper module re-exporting the enums with the anchoring utility", async () => {
        const files = await generate(specSets);

        const helper = fileAt(files, "index.ts");
        expect(helper?.contents).toContain(
          'import { ConTraceables } from "./ConTraceables.js";',
        );
        expect(helper?.contents).toContain(
          'import { SwTraceables } from "./SwTraceables.js";',
        );
        expect(helper?.contents).toContain(
          "export { ConTraceables, SwTraceables };",
        );
        expect(helper?.contents).toContain(
          "export type TraceableId = ConTraceables | SwTraceables;",
        );
        expect(helper?.contents).toContain(
          "export type TraceableIds = TraceableId | readonly [TraceableId, ...TraceableId[]];",
        );
        expect(helper?.contents).toContain(
          "export function traces<Value>(ids: TraceableIds, value: Value): Value;",
        );
        // The decorator overload: ids only, returning a no-op class/method decorator.
        expect(helper?.contents).toContain(
          "): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;",
        );
        expect(helper?.contents).toContain(
          "export function verifies(ids: TraceableIds, run: () => void)",
        );
        // The concerns relation: a function/decorator marker and a type marker.
        expect(helper?.contents).toContain(
          "export function concerns<Value>(ids: TraceableIds, value: Value): Value;",
        );
        expect(helper?.contents).toContain(
          "export type Concerns<Id extends TraceableIds, T> = T & { readonly __concerns?: Id };",
        );
        expect(helper?.contents).toContain(
          "export type Traces<Id extends TraceableIds, T> = T & { readonly __traces?: Id };",
        );
        // The JSDoc examples use a real member drawn from the first traceable.
        expect(helper?.contents).toContain("@example");
        expect(helper?.contents).toContain("ConTraceables.CON_012_OWNED");
      });

      test("emits one file per set plus the helper module", async () => {
        const files = await generate(specSets);

        expect(files.map((file) => file.path)).toEqual([
          "ConTraceables.ts",
          "SwTraceables.ts",
          "index.ts",
        ]);
      });

      test("is deterministic: the same spec sets produce byte-identical output", async () => {
        const first = await generate(specSets);
        const second = await generate(specSets);

        expect(second).toEqual(first);
      });
    },
  );
});
