import type { GeneratedFile, Generator, SpecSet } from "@ariadne-thread/core";

/** Where the TypeScript traceables file is written, relative to the output root. */
const OUTPUT_PATH = "ariadne/generated/traceables.ts";

/**
 * The TypeScript generator (ARCH-003; STR-011 skeleton). It emits, per spec set,
 * a union type of that set's ids, a `TraceableId` union composed from the sets
 * (not a flat list), and the anchoring utility — `Traces`, `traces`, `verifies`
 * — constrained to `TraceableId`, so a reference to a missing id fails to build.
 * This is a first working emission, not a complete generator.
 */
export function createTypeScriptGenerator(): Generator {
  return {
    name: "typescript",
    generate(specSets: readonly SpecSet[]): Promise<readonly GeneratedFile[]> {
      return Promise.resolve([renderTraceablesFile(specSets)]);
    },
  };
}

function renderTraceablesFile(specSets: readonly SpecSet[]): GeneratedFile {
  const lines: string[] = ["// Generated by ariadne. Do not edit.", ""];
  const setTypeNames: string[] = [];

  for (const specSet of specSets) {
    const typeName = `${toPascalCase(specSet.name)}TraceableId`;
    setTypeNames.push(typeName);
    const members = specSet.traceables.map(
      (traceable) => `  | ${JSON.stringify(traceable.id)}`,
    );
    lines.push(`export type ${typeName} =`);
    lines.push(members.length > 0 ? `${members.join("\n")};` : "  never;");
    lines.push("");
  }

  const union = setTypeNames.length > 0 ? setTypeNames.join(" | ") : "never";
  lines.push(`export type TraceableId = ${union};`);
  lines.push("");
  lines.push(
    "export type Traces<Id extends TraceableId, T> = T & { readonly __traces?: Id };",
  );
  lines.push(
    "export function traces<Id extends TraceableId, T>(_id: Id, value: T): Traces<Id, T> {",
  );
  lines.push("  return value;");
  lines.push("}");
  lines.push(
    "export function verifies<Id extends TraceableId>(_id: Id, run: () => void): void {",
  );
  lines.push("  run();");
  lines.push("}");
  lines.push("");

  return { path: OUTPUT_PATH, contents: lines.join("\n") };
}

/** Renders a lens id such as `SW` or `CON` as a PascalCase type-name fragment. */
function toPascalCase(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part[0]?.toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}
