/*
 * THIS FILE IS GENERATED BY ARIADNE-THREAD - DO NOT EDIT MANUALLY
 *
 * Run `ariadne spec` to regenerate.
 *
 * @ariadne-thread homepage: https://ariadne-thread.io
 * @ariadne-thread connector-type: req-as-code
 * @ariadne-thread generator-type: typescript
 * @ariadne-thread spec-set: ARCH
 */

export enum ArchTraceables {
  ARCH_001_PLUGGABLE_ID_STRATEGY = "ARCH-001",
  ARCH_002_STABLE_ERROR_CODES = "ARCH-002",
  ARCH_003_GENERATOR_INTERFACE = "ARCH-003",
}
