/*
 * THIS FILE IS GENERATED BY ARIADNE-THREAD - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @ariadne-thread homepage: https://ariadne-thread.io
 * @ariadne-thread connector-type: req-as-code
 * @ariadne-thread generator-type: typescript
 */

import { ArchTraceables } from "./ArchTraceables.js";
import { ConTraceables } from "./ConTraceables.js";
import { NfTraceables } from "./NfTraceables.js";
import { SwTraceables } from "./SwTraceables.js";

export { ArchTraceables, ConTraceables, NfTraceables, SwTraceables };

export type TraceableId = ArchTraceables | ConTraceables | NfTraceables | SwTraceables;

/** A single id, or a non-empty list of ids — an anchor must name at least one spec. */
export type TraceableIds = TraceableId | readonly [TraceableId, ...TraceableId[]];

// The three relations and every marker form are documented in the README.md
// in this folder (ADR-0004).

/**
 * Marks a type or interface as **realizing** one or more spec ids; the type is unchanged.
 *
 * @example
 * type AnchoredState = Realizes<ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, { sequences: number[] }>;
 *
 * @example
 * interface IdStrategy extends Realizes<ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, {}> { mint(): void; }
 */
export type Realizes<Id extends TraceableIds, T> = T & { readonly __realizes?: Id };

/**
 * Marks a type or interface as **concerning** one or more spec ids — coupled to
 * the spec without realizing it; the type is unchanged.
 *
 * @example
 * interface IdStrategy extends Concerns<ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, {}> { mint(): void; }
 */
export type Concerns<Id extends TraceableIds, T> = T & { readonly __concerns?: Id };

/**
 * Anchors code that **realizes** one or more spec ids; a removed id fails to compile.
 *
 * Called with a value it returns the value unchanged (wrap a function or
 * constant). Called with only the ids it returns a no-op decorator (annotate a
 * class or method).
 *
 * @example
 * export const mint = realizes(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, (type: string, count: number): string[] => []);
 *
 * @example
 * class Minter { @realizes(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY) mint() {} }
 */
export function realizes<Value>(ids: TraceableIds, value: Value): Value;
export function realizes(
  ids: TraceableIds,
): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;
export function realizes(_ids: TraceableIds, ...rest: unknown[]): unknown {
  if (rest.length === 1) {
    return rest[0];
  }
  return () => {};
}

/**
 * Anchors code that **concerns** one or more spec ids — coupled to the spec
 * without realizing or verifying it; a removed id fails to compile.
 *
 * Same two forms as `realizes`: a value or function wrapper, or — called with
 * only the ids — a no-op class/method decorator. The anchor is existence-checked
 * only; nothing exercises it (ADR-0004).
 *
 * @example
 * export const render = concerns(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, (n: number): string => String(n));
 *
 * @example
 * class Minter { @concerns(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY) render() {} }
 */
export function concerns<Value>(ids: TraceableIds, value: Value): Value;
export function concerns(
  ids: TraceableIds,
): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;
export function concerns(_ids: TraceableIds, ...rest: unknown[]): unknown {
  if (rest.length === 1) {
    return rest[0];
  }
  return () => {};
}

/**
 * Anchors a test that **verifies** one or more spec ids and runs it unchanged.
 *
 * @example
 * verifies(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, () => { test("holds", () => {}); });
 */
export function verifies(ids: TraceableIds, run: () => void): void {
  run();
}
