/*
 * THIS FILE IS GENERATED BY ARIADNE-THREAD - DO NOT EDIT MANUALLY
 *
 * Run `ariadne spec` to regenerate.
 *
 * @ariadne-thread homepage: https://ariadne-thread.io
 * @ariadne-thread connector-type: req-as-code
 * @ariadne-thread generator-type: typescript
 */

import { ArchTraceables } from "./ArchTraceables.js";
import { ConTraceables } from "./ConTraceables.js";
import { NfTraceables } from "./NfTraceables.js";
import { SwTraceables } from "./SwTraceables.js";

export { ArchTraceables, ConTraceables, NfTraceables, SwTraceables };

export type TraceableId = ArchTraceables | ConTraceables | NfTraceables | SwTraceables;

/** A single id, or a non-empty list of ids — an anchor must name at least one spec. */
export type TraceableIds = TraceableId | readonly [TraceableId, ...TraceableId[]];

/**
 * Marks a type as tracing one or more spec ids; the type is unchanged.
 *
 * @example
 * type AnchoredState = Traces<ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, { sequences: number[] }>;
 */
export type Traces<Id extends TraceableId, T> = T & { readonly __traces?: Id };

/**
 * Anchors code to one or more spec ids; a removed id fails to compile.
 *
 * Called with a value it returns the value unchanged (wrap a function or
 * constant). Called with only the ids it returns a no-op decorator (annotate a
 * class or method). Either way the ids are referenced, so deleting a spec
 * breaks the anchor.
 *
 * @example
 * export const mint = traces(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, (type: string, count: number): string[] => []);
 *
 * @example
 * class Minter { @traces(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY) mint() {} }
 */
export function traces<Value>(ids: TraceableIds, value: Value): Value;
export function traces(
  ids: TraceableIds,
): (target: unknown, propertyKey?: unknown, descriptor?: unknown) => void;
export function traces(_ids: TraceableIds, ...rest: unknown[]): unknown {
  if (rest.length === 1) {
    return rest[0];
  }
  return () => {};
}

/**
 * Anchors a test to one or more spec ids and runs it unchanged.
 *
 * @example
 * verifies(ArchTraceables.ARCH_001_PLUGGABLE_ID_STRATEGY, () => { test("holds", () => {}); });
 */
export function verifies(ids: TraceableIds, run: () => void): void {
  run();
}
