/*
 * THIS FILE IS GENERATED BY ARIADNE-THREAD - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @ariadne-thread homepage: https://ariadne-thread.io
 * @ariadne-thread connector-type: req-as-code
 * @ariadne-thread generator-type: typescript
 * @ariadne-thread spec-set: NF
 */

export enum NfTraceables {
  NF_001_STATE_ACCESS_MUTUALLY_EXCLUSIVE = "NF-001",
  NF_002_ATOMIC_STATE_WRITE = "NF-002",
}
