/*
 * THIS FILE IS GENERATED BY ARIADNE-THREAD - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @ariadne-thread homepage: https://ariadne-thread.io
 * @ariadne-thread connector-type: req-as-code
 * @ariadne-thread generator-type: typescript
 * @ariadne-thread spec-set: SYS
 */

export enum SysTraceables {
  SYS_001_COMPILE_CHECKED_ANCHORING = "SYS-001",
  SYS_002_REVERSE_TRACEABILITY_COVERAGE = "SYS-002",
  SYS_003_STABLE_SPEC_IDENTITY = "SYS-003",
  SYS_004_CONFIGURATION_AND_STATE = "SYS-004",
  SYS_005_SPEC_LIFECYCLE = "SYS-005",
  SYS_006_DIAGNOSTIC_CLARITY = "SYS-006",
  SYS_008_LANGUAGE_NEUTRAL_EXTENSIBILITY = "SYS-008",
  SYS_010_CONFIGURABLE_LENSES = "SYS-010",
  SYS_011_NAMED_ANCHOR_RELATIONS = "SYS-011",
  SYS_012_COVERAGE_POLICY_AND_WAIVERS = "SYS-012",
  SYS_013_SHARED_SCHEMAS = "SYS-013",
}
