/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: typescript
 * @clew spec-set: ENT
 */

export enum EntTraceables {
  ENT_001_ARIADNE_STATE = "ENT-001",
  ENT_002_CONFIGURATION = "ENT-002",
}
