/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: typescript
 * @clew spec-set: NF
 */

export enum NfTraceables {
  NF_001_STATE_ACCESS_MUTUALLY_EXCLUSIVE = "NF-001",
  NF_002_ATOMIC_STATE_WRITE = "NF-002",
}
