/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: typescript
 * @clew spec-set: STK
 */

export enum StkTraceables {
  STK_001_IMPLEMENTATION_ASSURANCE = "STK-001",
  STK_002_AUDIT_EVIDENCE = "STK-002",
  STK_003_LOW_AUTHORING_FRICTION = "STK-003",
  STK_004_TRACEABILITY_WITH_THE_CODE = "STK-004",
  STK_006_PROJECT_CONTROLLED_VOCABULARY = "STK-006",
  STK_007_SCRIPTABLE_DIAGNOSTICS = "STK-007",
  STK_008_POLYGLOT_APPLICABILITY = "STK-008",
}
