/**
 * The language emission seam (ARCH-003; STR-011).
 * Emitting the traceable symbols and the anchoring utility for a target language
 * is the job of a language-specific generator, chosen by configuration and
 * implemented behind this narrow interface. The core depends only on this
 * interface, never on a concrete generator — the boundary that must not erode
 * (ADR-0001 D9). It is the sibling of the id-generation seam (IdStrategy,
 * ARCH-001): same shape, but for language emission rather than the id's variable
 * part.
 */

/**
 * A single scanned spec: its id, its lens (its prefix), and the filename it was
 * declared in (SW-013). The filename is what spec-set matchers match against, so
 * a grouping can select on the descriptive slug, not only the sparse id (whose
 * only matchable part is the lens prefix).
 */
export interface Traceable {
  readonly id: string;
  readonly lens: string;
  readonly filename: string;
}

/**
 * A configured grouping of traceables a generator emits as one symbol set
 * (SW-013, ARCH-003). Grouping is by lens by default; the configurable grouping
 * rules are the follow-on story (STR-012) and are not built here.
 */
export interface SpecSet {
  /** The set's name; the lens id when grouping by lens (the default). */
  readonly name: string;
  readonly traceables: readonly Traceable[];
}

/**
 * A file a generator produces. The path is the file's name within the project's
 * configured output directory (ENT-002); the core joins it under that directory
 * and writes the bytes, so the generator decides filenames and the core decides
 * the location, and the core carries no language knowledge (SW-014).
 */
export interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

/** Context the core passes to a generator: the resolved directory its files will be written into (ENT-002). */
export interface GenerateContext {
  readonly outputDir: string;
}

/**
 * A language-specific generator (ARCH-003). Given the traceables grouped into
 * spec sets, it produces the verifiable symbols — one symbol set per spec set,
 * not a single flat list — and the anchoring utility that lets code mark a type,
 * a value, or a test against a spec id, constrained to those symbols. It is told
 * where its files will land (the context) so it can emit correct internal
 * references, such as a Java package matching the output directory.
 */
export interface Generator {
  /** Stable name matched against a configured generator's `type`. */
  readonly name: string;
  /**
   * The directory this generator writes into when a configured generator does
   * not set its own `outputDir` (ENT-002) — the generator's idiomatic location
   * for the target language. The core reads it as an opaque path.
   */
  readonly defaultOutputDir: string;
  /** Emits the traceable symbols and the anchoring utility for the spec sets. */
  generate(
    specSets: readonly SpecSet[],
    context: GenerateContext,
  ): Promise<readonly GeneratedFile[]>;
}

/**
 * The marker every generated file's banner carries (CON-012). The core uses it to
 * recognize, and prune, files it generated in a previous run that are no longer
 * emitted — so a removed spec set's stale file does not linger.
 */
export const GENERATED_MARKER = "GENERATED BY ARIADNE-THREAD";

/** The project homepage, recorded in the provenance banner. */
const HOMEPAGE = "https://ariadne-thread.io";

/**
 * The generated-file banner shared by every generator: a do-not-edit warning
 * (carrying GENERATED_MARKER), a regenerate hint, and `@ariadne-thread` provenance
 * annotations. A per-set file also carries its spec set. The banner is static, so
 * regeneration stays byte-identical (CON-012). The lines are a `/* … *\/` block —
 * valid in both TypeScript and Java — so all generators share one provenance
 * format. The caller wraps these lines in nothing further; it returns the full
 * comment.
 */
export function generatedHeader(
  generatorType: string,
  specSet?: string,
): string[] {
  const lines = [
    "/*",
    ` * THIS FILE IS ${GENERATED_MARKER} - DO NOT EDIT MANUALLY`,
    " *",
    " * Run `ariadne spec` to regenerate.",
    " *",
    ` * @ariadne-thread homepage: ${HOMEPAGE}`,
    " * @ariadne-thread connector-type: req-as-code",
    ` * @ariadne-thread generator-type: ${generatorType}`,
  ];
  if (specSet !== undefined) {
    lines.push(` * @ariadne-thread spec-set: ${specSet}`);
  }
  lines.push(" */");
  return lines;
}
