import type { SpecSet } from "@ariadne-thread/core";
import { ArchTraceables, SysTraceables, verifies } from "@ariadne-thread/trace";
import { describe, expect, test } from "vitest";
import { createJavaGenerator } from "./index.js";

const specSets: SpecSet[] = [
  {
    name: "SW",
    traceables: [{ id: "SW-002", lens: "SW", filename: "SW-002-mint-ids.md" }],
  },
];

describe("java generator output", () => {
  verifies(
    [
      ArchTraceables.ARCH_003_GENERATOR_INTERFACE,
      SysTraceables.SYS_008_LANGUAGE_NEUTRAL_EXTENSIBILITY,
    ],
    () => {
      test("derives the package from the output directory and names constants from filenames", async () => {
        const [file] = await createJavaGenerator().generate(specSets, {
          outputDir: "src/main/java/ariadne/traceables",
        });

        expect(file?.path).toBe("Traceables.java");
        expect(file?.contents).toContain("package ariadne.traceables;");
        expect(file?.contents).toContain('SW_002_MINT_IDS("SW-002")');
        expect(file?.contents).toContain(
          "THIS FILE IS GENERATED BY ARIADNE-THREAD",
        );
        expect(file?.contents).toContain(
          "@ariadne-thread generator-type: java",
        );
      });

      test("strips a leading src/ root when deriving the package", async () => {
        const [file] = await createJavaGenerator().generate(specSets, {
          outputDir: "src/ariadne/traceables",
        });

        expect(file?.contents).toContain("package ariadne.traceables;");
      });

      test("declares its default output directory", () => {
        expect(createJavaGenerator().defaultOutputDir).toBe(
          "src/main/java/ariadne/traceables",
        );
      });
    },
  );
});
