import type { GeneratedFile, Generator, SpecSet } from "@ariadne-thread/core";

/** Where the Java traceables file is written, relative to the output root. */
const OUTPUT_PATH = "ariadne/generated/Traceables.java";

/**
 * The Java generator (ARCH-003; STR-011 skeleton). It emits one `Traceables`
 * class holding, per spec set, a nested enum whose constants are that set's ids
 * — one symbol set per spec set, not a single flat list — each carrying its id
 * string. This is a first working emission, not a complete generator; the full
 * anchoring utility is iterated later.
 */
export function createJavaGenerator(): Generator {
  return {
    name: "java",
    generate(specSets: readonly SpecSet[]): Promise<readonly GeneratedFile[]> {
      return Promise.resolve([renderTraceablesFile(specSets)]);
    },
  };
}

function renderTraceablesFile(specSets: readonly SpecSet[]): GeneratedFile {
  const lines: string[] = [
    "// Generated by ariadne. Do not edit.",
    "package ariadne.generated;",
    "",
    "public final class Traceables {",
    "  private Traceables() {}",
  ];

  for (const specSet of specSets) {
    const enumName = toPascalCase(specSet.name);
    const constants = specSet.traceables.map(
      (traceable) =>
        `    ${toConstantName(traceable.id)}(${JSON.stringify(traceable.id)})`,
    );
    lines.push("");
    lines.push(`  public enum ${enumName} {`);
    lines.push(`${constants.join(",\n")};`);
    lines.push("");
    lines.push("    private final String id;");
    lines.push("");
    lines.push(`    ${enumName}(String id) {`);
    lines.push("      this.id = id;");
    lines.push("    }");
    lines.push("");
    lines.push("    public String id() {");
    lines.push("      return this.id;");
    lines.push("    }");
    lines.push("  }");
  }

  lines.push("}");
  lines.push("");
  return { path: OUTPUT_PATH, contents: lines.join("\n") };
}

/** Renders a lens id such as `SW` as a PascalCase Java type-name fragment. */
function toPascalCase(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part[0]?.toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

/** Renders a spec id such as `SW-013` as a Java enum-constant name `SW_013`. */
function toConstantName(id: string): string {
  return id.replace(/[^A-Za-z0-9]+/g, "_");
}
